name: Deploy to DigitalOcean

on:
  push:
    branches: [production]

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e  # Exit if any command fails

            cd /root/agent-builder
            git pull origin production

            source venv/bin/activate
            pip install -r requirements.txt

            # Restart backend
            pm2 restart backend-api

            # Build frontend
            cd frontend
            npm install
            npm run build

            # Restart frontend (if using PM2)
            pm2 restart SCORE

          EOF
